AWSTemplateFormatVersion : '2010-09-09'
Transform: "AWS::Serverless-2016-10-31"
Resources:
  CsvReader:
    Type: "AWS::Serverless::Function"
    Properties:
      Runtime: 'nodejs10.x'
      Handler: 'handler.hello'
      CodeUri: './csvreader-api/handler.js'
      Policies: 'OnlyFileReadCsv'
      Events:
        MyApiRequest:
          Type: Api
          Properties:
            Path: /
            Method: get